# Generated by Django 3.2.5 on 2021-07-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пива')),
                ('style_id', models.PositiveSmallIntegerField(verbose_name='Id стиля пива')),
                ('abv', models.PositiveSmallIntegerField(verbose_name='Крепость пива')),
                ('ibu', models.PositiveSmallIntegerField(verbose_name='Горечь пива')),
            ],
        ),
        migrations.CreateModel(
            name='BeerBrewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_id', models.PositiveSmallIntegerField(verbose_name='Id пива')),
                ('brewery_id', models.PositiveSmallIntegerField(verbose_name='Id пивоварни')),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пивоварни')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес пивоварни')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('state', models.CharField(max_length=50, verbose_name='Штат')),
                ('code', models.CharField(max_length=20, verbose_name='Индекс')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('website', models.CharField(max_length=100, verbose_name='Сайт')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название магазина')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('owners_name', models.CharField(max_length=50, verbose_name='Имя владельца')),
            ],
        ),
    ]
