# Generated by Django 3.2.5 on 2021-07-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0002_beer_beerbrewery_brewery_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес пивоварни'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='code',
            field=models.CharField(max_length=20, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название пивоварни'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='state',
            field=models.CharField(max_length=50, null=True, verbose_name='Штат'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='website',
            field=models.CharField(max_length=100, null=True, verbose_name='Сайт'),
        ),
    ]
