# Generated by Django 3.2.5 on 2021-07-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0003_auto_20210720_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='style_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_app.style', verbose_name='Id стиля пива'),
        ),
    ]
