# Generated by Django 3.2.5 on 2021-07-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0004_alter_beer_style_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerbrewery',
            name='beer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_app.beer', verbose_name='Id пива'),
        ),
        migrations.AlterField(
            model_name='beerbrewery',
            name='brewery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_app.brewery', verbose_name='Id пивоварни'),
        ),
    ]
