# Generated by Django 3.2.5 on 2021-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0006_beer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(default='beer_not_found.png', upload_to='images'),
        ),
    ]
