# Generated by Django 3.2.5 on 2021-08-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0008_alter_beer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(default='beer_not_found.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='beerbrewery',
            name='beer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_relate', to='beer_app.beer', verbose_name='Id пива'),
        ),
        migrations.AlterField(
            model_name='beerbrewery',
            name='brewery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brewery_relate', to='beer_app.brewery', verbose_name='Id пивоварни'),
        ),
    ]
