# Generated by Django 3.2.5 on 2021-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0011_auto_20210826_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
        migrations.AlterField(
            model_name='profile',
            name='beer',
            field=models.JSONField(default={}),
        ),
    ]
